#version: '2'
services:

  # POSTGRES PAYMENT
  postgres:
    container_name: postgres
    image: postgres
    ports:
        - "5433:5432"
    environment:
        POSTGRES_DB: "payments"
        POSTGRES_PASSWORD: "password"
        POSTGRES_USER: "postgres"
    restart: always

  # RABBITMQ 
  rabbit:
      container_name: rabbitmq
      image: rabbitmq:3.7-management
      ports:
          - "15673:15672"
      restart: always

  # GATEWAY
  gateway:
    container_name: gateway
    build: ./gateway
    depends_on:
      - rabbit
    ports:
        - "8003:8000"
    links:
        - rabbit
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"
        RABBIT_MANAGEMENT_PORT: "15672"

  # PAYMENTS
  payments:
    container_name: payments
    build: ./payments
    depends_on:
      - rabbit
      - postgres
    ports:
        - "8001:8000"
    links:
        - rabbit
        - postgres
    environment:
        DB_PASSWORD: "password"
        DB_USER: "postgres"
        DB_HOST: "postgres"
        DB_NAME: "payments"
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"
        RABBIT_MANAGEMENT_PORT: "15672"

networks:
  default:
    name: payment
    external: true
